{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "chrisalvis-me.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chrisalvis-me.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gateway.name }}
      namespace: {{ .Values.httproute.gateway.namespace }}
  hostnames:
    - {{ .Values.httproute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "chrisalvis-me.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
